In [4]:
import pandas as pd

exceptions = pd.read_csv('../data/cpd_Exceptions.csv')
exceptions.head()

,Source Plate Name,Source Plate Barcode,Source Plate Type,Source Well,Destination Plate Name,Destination Plate Barcode,Destination Plate Type,Destination Well,Destination Well X Offset,Destination Well Y Offset,Sample ID,Sample Name,Transfer Volume,Actual Volume,Current Fluid Volume,Fluid Composition,Fluid Units,Fluid Type,Transfer Status
0,Source[2],NaN,384LDV_DMSO,H7,Destination[2],NaN,384PP_Dest,F8,0,0,NaN,NaN,1500.0,0,0.0,0.0,Percent,DMSO,MM0202007: Problem calc. well fluid volume fc:...
1,Source[2],NaN,384LDV_DMSO,H7,Destination[2],NaN,384PP_Dest,F7,0,0,NaN,NaN,945.0,0,0.0,0.0,Percent,DMSO,MM0202007: Problem calc. well fluid volume fc:...
2,Source[2],NaN,384LDV_DMSO,H7,Destination[2],NaN,384PP_Dest,F6,0,0,NaN,NaN,547.5,0,0.0,0.0,Percent,DMSO,MM0202007: Problem calc. well fluid volume fc:...
3,Source[2],NaN,384LDV_DMSO,H7,Destination[2],NaN,384PP_Dest,F5,0,0,NaN,NaN,280.0,0,0.0,0.0,Percent,DMSO,MM0202007: Problem calc. well fluid volume fc:...
4,Source[2],NaN,384LDV_DMSO,H7,Destination[2],NaN,384PP_Dest,F4,0,0,NaN,NaN,117.5,0,0.0,0.0,Percent,DMSO,MM0202007: Problem calc. well fluid volume fc:...

In [6]:
picklist = pd.read_csv('../design/cpd-src-picklist.csv', index_col=0)
picklist.head()

  SrcPlate SrcWell Destination Plate Name DestWell  Transfer Volume /nl
0     src1      G1         dest-bsa-blank       A2                  5.0
1     src1      G1         dest-bsa-blank       A3                 35.0
2     src1      G1         dest-bsa-blank       A4                117.5
3     src1      G1         dest-bsa-blank       A5                280.0
4     src1      G1         dest-bsa-blank       A6                547.5

In [12]:
src = pd.read_csv('../design/src_layout.csv')
src.head()

,Item Name,CatalogNumber,Rack Number,Plate Location,Src Wells
0,Bezafibrate,S4159,L1300-10,e6,"['G1', 'G2']"
1,Pranlukast,S1829,L1300-04,c9,"['G3', 'G4']"
2,Cyclandelate,S4189,L1300-10,f9,"['G5', 'G6']"
3,norethindrone,S4040,L1300-09,e8,"['G7', 'G8']"
4,Esomeprazole magnesium (Nexium),S1743,L1300-04,a4,"['G9', 'G10']"